---
language: generic
dist: xenial
os: linux

cache:
  directories:
    - "$HOME/.stack"

script:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - stack --no-terminal install hlint pandoc stylish-haskell happy
  - travis_retry curl -L https://github.com/rubik/stack-hpc-coveralls/releases/download/v0.0.4.0/shc-linux-x64-7.10.3.tar.bz2 | tar -xj -C $HOME/.local/bin
  - cp -a bin $HOME/.local/
  # TODO(iphydf): Figure out how to do this more generically. How were we supposed
  # to know that this file is needed and can be found here?
  - cp $HOME/.stack/snapshots/x86_64-linux/*/8.8.2/share/x86_64-linux-ghc-8.8.2/hlint-2.2.11/hlint.yaml $HOME/.local/bin/data/
  - (WORK=`pwd` && cd $HOME && tar zcf $WORK/hs-tools-$TRAVIS_TAG.tar.gz -C $HOME
      .local/bin
      .stack/snapshots/x86_64-linux/*/8.8.2/share/x86_64-linux-ghc-8.8.2/happy-1.19.12
      .stack/snapshots/x86_64-linux/*/8.8.2/share/x86_64-linux-ghc-8.8.2/hlint-2.2.11
      .stack/snapshots/x86_64-linux/*/8.8.2/share/x86_64-linux-ghc-8.8.2/pandoc-2.9.1.1)

deploy:
  provider: releases
  token:
    secure: "TOrUHMITxq2881owr+pe7VlTb4fKHBmnZYm3Vc0+ldK8eF2+D/cg74gA9spDCML95d1hwLJnq9sWnZrndE9Gmpts/uaJyjVQEzcOBE6O4hS1xJI6/2Uq0tJ+/4uu4YL18qbtWhFKjUBaXb4Cu8noAcDrrLUAeQ/VkHsg7E1aFkqIkapb69hPOacDiwZNeUEUX2kIJp3maGKkTSOA9soTTYA/O1Np84SF/xy4j7mGGr1ZmuWONAYnf0m7/dNwrBRy6FALjGhVc6UfBa7NOYf0KJImWlpNtzWffM5+c/Ym9JovlQgO7WBAJW/fQGK67EtPD/dckCFgv2hc57n618/JaWP3ooR/zVE7p1Ny4VXbMZLTM4X6L8kV5NexmFV0SSKn5BCWgcLehSkSgzi6GITeBi6Et/x/x7hO/4qRcKft5sH3hvHoBVzKZDut72Crcix5baDbEIbnLC3YRdaa/JBYMDE0xxG7y+3wVppw4+6g2vOVbacmG9w9w2vM4DAcUFhhJmjmoB5/IzneJvjChoMFo8mrP9JMZfFZBLfX5etJ4msJIPXfmxYWoMD2dcguxGp3VeWvPLFFY6hefZq9wPq2XHy2baGSN+vNUwe9vRqJQNGePNQBWAYTdBedmfAuz1mnDDuv1wvWOzio/nRDLvaBZCxk5wgj8VUjTl1SRUe4fGI="
  file: hs-tools-$TRAVIS_TAG.tar.gz
  skip_cleanup: true
  on:
    repo: TokTok/hs-tools
    tags: true

# Only build pull requests and releases, don't build master on pushes,
# except through api or cron.
if: type IN (pull_request, api, cron) OR tag IS present
